//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kursovayaEntities : DbContext
    {
        public kursovayaEntities()
            : base("name=kursovayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeLimit> AgeLimit { get; set; }
        public virtual DbSet<CategoryShow> CategoryShow { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<NameShow> NameShow { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Show> Show { get; set; }
        public virtual DbSet<StatusShow> StatusShow { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
