//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NameShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NameShow()
        {
            this.Show = new HashSet<Show>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public int AgeLimitID { get; set; }
        public string Photo { get; set; }
        public int CategoryShowID { get; set; }
        public string Address { get; set; }
        public bool IsPayout { get; set; }
    public string IsPayoutText
        {
            get
            {
                return IsPayout == true ? "С оплатой" : "Без оплаты";
            }
        }
        public double? AverageRating
        {
            get
            {
                return Show.Select(s => s.Record.Average(r => r.Rating)).Sum();
            }
        }
        public virtual AgeLimit AgeLimit { get; set; }
        public virtual CategoryShow CategoryShow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show> Show { get; set; }
    }
}
